version: "3.1"

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "3000:3000"
    volumes:
    - ./src:/app/src
    depends_on:
    - mongo
    - sqlite
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    logging:
      options:
        max-size: 1g
    volumes:
      - ./db/db_data/:/db/
  sqlite:
    image: alpine:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/db_data:/data
    command: sh -c "apk --no-cache add sqlite && sqlite3 && tail -f /dev/null"
    container_name: sqlite-container