version: "3.1"

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "3000:3000"
    volumes:
    - ./src:/app/src
    depends_on:
    - mongo
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    logging:
      options:
        max-size: 1g
    volumes:
      - ./src/db/db_data/:/db/